apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::637423414709:role/tfnodegrouprole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::637423414709:user/pablo
      username: pablo
      groups: []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

#userarn gets tied to a kubernetes username (line11)