apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  namespace: web-apps
spec:
  type: NodePort #type of service (NodePort that exposes services on your nodes)
  selector: #who is this service routing to
      pod: nginx #should match label of pod; who it will forward to
  ports:
  - protocol: TCP
    port: 80 #port that service is listening on
    targetPort: 80 #open port of the pod
    nodePort: 31030 #range must be between 30000-32767