apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: #"namespace" imitted since ClusterRoles are not namespaced
  name: node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]