apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-deployment-service-reader
  namespace: web-apps
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "services"]
  verbs: ["get", "list"]