apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-cluster-binding
subjects:
- kind: User 
  name: k8tfuser
  apiGroups: rbac.authorization.k8s.io #organizes groups together and resources; grouping
roleRef:
  kind: ClusterRole
  name: admin-cluster
  apiGroups: rbac.authorization.k8s.io